openapi: 3.0.0
info:
  title: Todo Rest API
  description: TodoアプリのAPI仕様書
  version: 1.0.0
paths:
  /todos:
    get:
      tags:
        - todos
      summary: Get all todos.
      description: Returns an array of Todo model
      parameters: []
      responses:
        '200':
          description: A JSON array of Todo model
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/InternalServerErrorResponse'                  
    post:
      tags: 
        - todos
      summary: 新しいタスクを作成
      description: Create a new todo
      parameters: []
      requestBody:
        description: user to create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoRequest'
      responses:
        '201':
          description: CREATED
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/InternalServerErrorResponse'            
  /todos/{todoId}:
    get:
      tags:
        - todos
      summary: TodoのIDの単体取得.
      description: Returns a Todo model
      parameters: 
        - name: todoId
          in: path
          description: Todo id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single Todo model
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Todo'
        '404':
          description: Not found
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/NotFoundResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/InternalServerErrorResponse'       
    put:
      tags:
        - todos
      summary: Todoの更新.
      description: Returns a updated Todo model
      parameters: 
        - name: todoId
          in: path
          description: Todo id
          required: true
          schema:
            type: integer
      requestBody:
        description: user to create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoRequest'
      responses:
        '204':
          description: Successfully updated
        '201':
          description: Successfully created
        '404':
          description: Not found
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/NotFoundResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/InternalServerErrorResponse'        
          
    delete:
      tags:
        - todos
      summary: Todoの削除.
      description: Returns a updated Todo model
      parameters: 
        - name: todoId
          in: path
          description: Todo id
          required: true
          schema:
            type: integer     
      responses:
        '204':
          description: Successfully deleted
        '404':
          description: Not found
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/NotFoundResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/InternalServerErrorResponse'        
                  
components:
  schemas:
    Todo:
      type: object
      required:
        - id
        - title
        - content
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        content:
          type: string
      example: 
        - id: 1
          title: 買い物
          content: Air Pods Proを買いに行く
    TodoRequest:
      type: object
      required:
        - title
        - content
      properties:
        title:
          type: string
        content:
          type: string
      example: 
        title: Lambdaについて学ぶ
        content: APIGatewayを使ったRESTAPIの作成。 
    NotFoundResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
      example: 
          message: todo not found        
    InternalServerErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
      example: 
          message: internal server error          
          
          
