AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
 
Globals:
  Function:
    Timeout: 15

Resources:
  GetTaskFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: tasks/
      Handler: handlers/getTask.findTaskHandler
      Runtime: nodejs10.x
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: ""
      Events:
        GetTasks:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /tasks/{task_id}
            Method: get
  GetTasksFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: tasks/
      Handler: handlers/getTask.lambdaHandler
      Runtime: nodejs10.x
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: ""
      Events:
        GetTaskss:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /tasks
            Method: get
  CreateTaskFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: tasks
      Handler: handlers/create.lambdaHandler
      Runtime: nodejs10.x
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: ""
      Events:
        CreateTask:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /tasks/
            Method: post
  UpdateTaskFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: tasks/
      Handler: handlers/update.lambdaHandler
      Runtime: nodejs10.x
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: ""
      Events:
        UpdateTasks:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /tasks/{task_id}
            Method: put
  DeleteTaskFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: tasks/
      Handler: handlers/delete.lambdaHandler
      Runtime: nodejs10.x
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: ""
      Events:
        DeleteTask:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /tasks/{task_id}
            Method: delete

Outputs:
  GetTaskApi:
    Description: "API Gateway endpoint URL for Prod stage for Task function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/tasks"
  GetTaskFunction:
    Description: "Get Task Lambda Function ARN"
    Value: !GetAtt GetTaskFunction.Arn
  GetTaskFunctionIamRole:
    Description: "Implicit IAM Role created for CreateTask function"
    Value: !GetAtt GetTaskFunctionRole.Arn
  GetTasksFunction:
    Description: "Get Tasks Lambda Function ARN"
    Value: !GetAtt GetTasksFunction.Arn
  GetTasksFunctionIamRole:
    Description: "Implicit IAM Role created for Get Task function"
    Value: !GetAtt GetTasksFunctionRole.Arn
  CreateTaskFunction:
    Description: "Create Task Lambda Function ARN"
    Value: !GetAtt CreateTaskFunction.Arn
  CreateTaskFunctionIamRole:
    Description: "Implicit IAM Role created for Create Task function"
    Value: !GetAtt CreateTaskFunctionRole.Arn
  UpdateTaskFunction:
    Description: "Update Task Lambda Function ARN"
    Value: !GetAtt UpdateTaskFunction.Arn
  UpdateTaskFunctionIamRole:
    Description: "Implicit IAM Role created for Update Task function"
    Value: !GetAtt UpdateTaskFunctionRole.Arn
  DeleteTaskFunction:
    Description: "Delete Task Lambda Function ARN"
    Value: !GetAtt DeleteTaskFunction.Arn
  DeleteTaskFunctionIamRole:
    Description: "Implicit IAM Role created for Delete Task function"
    Value: !GetAtt DeleteTaskFunctionRole.Arn
