AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
 
Globals:
  Function:
    Timeout: 15

Resources:
  GetTodoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: todos/
      Handler: handlers/getTodo.findTodoHandler
      Runtime: nodejs10.x
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: ""
      Events:
        GetTodos:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /todos/{todo_id}
            Method: get
  GetTodosFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: todos/
      Handler: handlers/getTodo.lambdaHandler
      Runtime: nodejs10.x
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: ""
      Events:
        GetTodoss:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /todos
            Method: get
  CreateTodoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: todos
      Handler: handlers/create.lambdaHandler
      Runtime: nodejs10.x
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: ""
      Events:
        CreateTodo:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /todos/
            Method: post
  UpdateTodoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: todos/
      Handler: handlers/update.lambdaHandler
      Runtime: nodejs10.x
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: ""
      Events:
        UpdateTodos:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /todos/{todo_id}
            Method: put
  DeleteTodoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: todos/
      Handler: handlers/delete.lambdaHandler
      Runtime: nodejs10.x
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: ""
      Events:
        DeleteTodo:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /todos/{todo_id}
            Method: delete

Outputs:
  GetTodoApi:
    Description: "API Gateway endpoint URL for Prod stage for Todo function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/todos"
  GetTodoFunction:
    Description: "Get Todo Lambda Function ARN"
    Value: !GetAtt GetTodoFunction.Arn
  GetTodoFunctionIamRole:
    Description: "Implicit IAM Role created for CreateTodo function"
    Value: !GetAtt GetTodoFunctionRole.Arn
  GetTodosFunction:
    Description: "Get Todos Lambda Function ARN"
    Value: !GetAtt GetTodosFunction.Arn
  GetTodosFunctionIamRole:
    Description: "Implicit IAM Role created for Get Todo function"
    Value: !GetAtt GetTodosFunctionRole.Arn
  CreateTodoFunction:
    Description: "Create Todo Lambda Function ARN"
    Value: !GetAtt CreateTodoFunction.Arn
  CreateTodoFunctionIamRole:
    Description: "Implicit IAM Role created for Create Todo function"
    Value: !GetAtt CreateTodoFunctionRole.Arn
  UpdateTodoFunction:
    Description: "Update Todo Lambda Function ARN"
    Value: !GetAtt UpdateTodoFunction.Arn
  UpdateTodoFunctionIamRole:
    Description: "Implicit IAM Role created for Update Todo function"
    Value: !GetAtt UpdateTodoFunctionRole.Arn
  DeleteTodoFunction:
    Description: "Delete Todo Lambda Function ARN"
    Value: !GetAtt DeleteTodoFunction.Arn
  DeleteTodoFunctionIamRole:
    Description: "Implicit IAM Role created for Delete Todo function"
    Value: !GetAtt DeleteTodoFunctionRole.Arn
