AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
 
Globals:
  Function:
    Timeout: 15

Resources:
  GetTaskFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: tasks/
      Handler: handlers/getTasks.lambdaHandler
      Runtime: nodejs10.x
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: "192.168.10.10:8000"       
      Events:
        GetTasks:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /tasks/{tasks_id}
            Method: get
  GetTasksFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: tasks/
      Handler: handlers/getTasks.lambdaHandler
      Runtime: nodejs10.x
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: "192.168.10.10:8000"       
      Events:
        GetTaskss:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /tasks
            Method: get
  UpdateTaskFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: tasks/
      Handler: handlers/update.lambdaHandler
      Runtime: nodejs10.x
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: "192.168.10.10:8000"       
      Events:
        UpdateTasks:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /tasks/{tasks_id}
            Method: patch
  DeleteTaskFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: tasks/
      Handler: handlers/delete.lambdaHandler
      Runtime: nodejs10.x
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: "192.168.10.10:8000"       
      Events:
        DeleteTask:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /tasks/{tasks_id}
            Method: delete
  CreateTaskFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: tasks
      Handler: handlers/create.lambdaHandler
      Runtime: nodejs10.x
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: "192.168.10.10:8000" 
      Events:
        CreateTask:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /tasks/
            Method: post



Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
